- platform: html5
  name: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id

#- platform: telegram
#  name: Telegram
#  api_key: !secret telegram_api_key
#  chat_id: !secret telegram_chat_id
