# CAMERA PACKAGE
# IP connected cameras
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------
    sensor.motion_indoor_camera_kitchen:
      icon: mdi:camcorder
      friendly_name: Kitchen

group:
#----------------------------------------------------------------

  cameras_all:
    - camera.kitchen

  cameras_group1:
    - camera.kitchen

android_ip_webcam:
  - name: Kitchen
    host: !secret kitchen_camera_url
    sensors: 
      - battery_level
