# HOME ASSISTANT PACKAGE
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    script.backup:
      icon: mdi:zip-box
      friendly_name: Backup Home Assistant
