# HOME ASSISTANT PACKAGE
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    script.backup:
      icon: mdi:zip-box
      friendly_name: Backup Home Assistant

automation:
#----------------------------------------------------------------

  # Notify when Home Assistant starts
  - alias: NOTIFY (START) Home Assistant
    hide_entity: True
    trigger:
      platform: event
      event_type: homeassistant_start
    condition:
      - condition: state
        entity_id: input_boolean.options_notifications_push
        state: 'on'
    action:
      - service: notify.html5
        data:
          message: "Home Assistant Started"
          title: ""
          target: 'William'

  # Notify when Home Assistant has a new update pending
  - alias: NOTIFY (UPDATE) Home Assistant
    hide_entity: True
    trigger:
      - platform: state
        entity_id: updater.updater
    condition:
      - condition: state
        entity_id: input_boolean.options_notifications_push
        state: 'on'
    action:
      - service: notify.html5
        data_template:
          message: "Home Assistant {{ states.updater.updater.state }} is now available."
          title: ""
          target: 'William'
