# RESIDENTS PACKAGE
# Notifies and performs automations when key residents arrive
#----------------------------------------------------------------
homeassistant:
  customize:
  #----------------------------------------------------------------

    sensor.tracker_william:
      icon: mdi:cellphone-android
      entity_picture: 
      friendly_name: William

    sensor.tracker_emily:
      icon: mdi:cellphone-android
      entity_picture: /local/emily.jpg
      friendly_name: Emily

group:
#----------------------------------------------------------------

  residents_all:
    name: Residents
    view: no
    icon: mdi:account-multiple
    entities:
    - sensor.tracker_william
    - sensor.tracker_emily

sensor:
#----------------------------------------------------------------

  # Every resident is "sensed" through device tracking of their phones.
  # Here I prioritize "sensing" their device connected to my home network
  # over what iCloud indicates
  #----------------------------------------------------------------
  - platform: template
    sensors:
      tracker_william:
        friendly_name: 'William'
        value_template: >-
          {% if is_state('device_tracker.william_phonewilliam', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

  - platform: template
    sensors:
      tracker_emily:
        friendly_name: 'Emily'
        value_template: >-
          {% if is_state('device_tracker.emily_phoneemily', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

automation:
#----------------------------------------------------------------

  # NOTIFICATIONS
  #----------------------------------------------------------------

  # Send a notification when key residents arrive
  - alias: NOTIFY (HOME) Resident
    initial_state: True # start disabled to avoid false positives on HA restart  
    hide_entity: True
    trigger:
      - platform: state
        entity_id:
          - sensor.tracker_william
          - sensor.tracker_emily
        to: 'Home'
    condition:
      - condition: state
        entity_id: input_boolean.options_notifications_push
        state: 'on'
    action:
      - service: notify.html5
        data_template:
          message: "{{ trigger.entity_id.split('.')[1].lower().replace('tracker_', '').title() }} is home"
          title: ""
          target: 'William'


  # Send a notification when key residents leave
  - alias: NOTIFY (AWAY) Resident
    initial_state: True # start disabled to avoid false positives on HA restart  
    hide_entity: True
    trigger:
      - platform: state
        entity_id:
          - sensor.tracker_william
          - sensor.tracker_emily
        from: 'Home'
    condition:
      - condition: state
        entity_id: input_boolean.options_notifications_push
        state: 'on'
    action:
      - service: notify.html5
        data_template:
          message: "{{ trigger.entity_id.split('.')[1].lower().replace('tracker_', '').title() }} is Away"
          title: ""
          target: 'William'


script: 
  refresh_devices:
    sequence:
      - service: mqtt.publish
        data:
          topic: "owntracks/william/phonewilliam"
          payload_template: '{"_type":"cmd","action":"reportLocation"}'
      - service: mqtt.publish
        data:
          topic: "owntracks/emily/phoneemily"
          payload_template: '{"_type":"cmd","action":"reportLocation"}'
