# RESIDENTS PACKAGE
# Notifies and performs automations when key residents arrive
#----------------------------------------------------------------
homeassistant:
  customize:
  #----------------------------------------------------------------

    sensor.tracker_william:
      icon: mdi:cellphone-android
      entity_picture:
      friendly_name: William

    sensor.tracker_emily:
      icon: mdi:cellphone-android
      entity_picture: /local/emily.jpg
      friendly_name: Emily

group:
#----------------------------------------------------------------

  residents_all:
    name: Residents
    view: no
    icon: mdi:account-multiple
    entities:
    - device_tracker.william_phonewilliam
    - device_tracker.emily_phoneemily

sensor:
#----------------------------------------------------------------

  # Every resident is "sensed" through device tracking of their phones.
  # Here I prioritize "sensing" their device connected to my home network
  # over what iCloud indicates
  #----------------------------------------------------------------
  - platform: template
    sensors:
      tracker_william:
        friendly_name: 'William'
        value_template: >-
          {% if is_state('device_tracker.william_phonewilliam', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

  - platform: template
    sensors:
      tracker_emily:
        friendly_name: 'Emily'
        value_template: >-
          {% if is_state('device_tracker.emily_phoneemily', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

script:
  refresh_devices:
    sequence:
      - service: mqtt.publish
        data:
          topic: "owntracks/william/phonewilliam"
          payload_template: '{"_type":"cmd","action":"reportLocation"}'
      - service: mqtt.publish
        data:
          topic: "owntracks/emily/phoneemily"
          payload_template: '{"_type":"cmd","action":"reportLocation"}'
