# VIDEO PLAYER PACKAGE
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    # LIVING ROOM
    #----------------------------------------------------------------
    media_player.living_room_tv:
      icon: mdi:television
      friendly_name: Living Room TV
      hidden: true

    media_player.plex_fd7dd5375df29783_com_plexapp_android:
      icon: mdi:plex
      friendly_name: Bed Room (Nexus Player)
      hidden: false

    media_player.plex_4mytcezzsiw9udi:
      icon: mdi:plex
      friendly_name: Lounge Room TV
      hidden: false

    #WEB
    #---------------------------------------------------------------
    media_player.plex_2a3b1bab_1c0b_4b0e_b009_2213bf9257f7:
      icon: mdi:google-chrome
      friendly_name: Work Laptop (Chrome)

    # MOBILE
    #----------------------------------------------------------------
    media_player.plex_21579ff9635937f3_com_plexapp_android:
      icon: mdi:plex
      friendly_name: William (Pixel)

    # TIM & BRI
    #---------------------------------------------------------------
    media_player.plex_i3gtg2r62yhnnrk9:
      icon: mdi:plex
      friendly_name: Tim & Bri

    # RON & DEB
    #--------------------------------------------------------------
    media_player.plex_e7a3x16bgqp72hfi754u9dx6r:
      icon: mdi:cast
      friendly_name: Ron & Deb
      
    media_player.plex_94335899_a01c_49a6_821f_0584e29a2ddf:
      icon: mdi:tablet-ipad
      friendly_name: Ron's iPad
    
    # JAZ
    #--------------------------------------------------------------
    media_player.plex_378e7227_b433_433e_84b9_98dadb7b990f:
      icon: mdi:plex
      friendly_name: Jaz
    
    # The Jonses
    #----------------
    media_player.plex_txr4o82xdrlf:
      icon: mdi:xbox
      friendly_name: The Jonses

sensor:
#----------------------------------------------------------------

  # Modified component to:
  # 1) Show player name if username is blank
  # 2) Show TV show, season, and episode number
  - platform: plex
    name: PlexSpy
    host: !secret plex_host
    port: !secret plex_port
    username: !secret plex_username
    password: !secret plex_password

media_player:
#----------------------------------------------------------------

  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    use_episode_art: false
    use_custom_entity_ids: true
    show_all_controls: false
    scan_interval: 5

  - platform: webostv
    host: 172.30.1.10
    name: Living Room TV
    customize:
      sources:
        - livetv
        - HDMI1
        - YouTube
        - Plex



